name: JaCoCo Badge

on:
  workflow_run:
    workflows: [ "Continuous integration" ]
    types: [ "completed" ]

permissions:
  contents: read

jobs:
  badge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Re-generate JaCoCo reports (XML/CSV)
        run: ./gradlew jacocoTestReport

      - name: Create JaCoCo badge (no commit)
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-xml-file: build/reports/jacoco/test/jacocoTestReport.xml
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-badges
          path: .github/badges/